baseurl         = "https://tbro28.github.io/brownsblog/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Brown's Blog"
  subtitle    = "Just a place to capture stuff."
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
#  cover       = "img/banner.png"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "tbro28"
  linkedinName = "eueung"
  mediumName = ""

  logo = "banner55.jpg"
#  logo = "hugo-logo.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Tim"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Seattle, WA"
  authorWebsite = "https://tbro28.github.io"
  authorDescription = "Have the attitude and honest belief that if you give it your all it will be done."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

#[[menu.main]]
#  name = "Go"
#  url = "/tags/golang/"
#  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 99

#[[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 95
